kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: control-api
subjects:
  - kind: ServiceAccount
    name: control-api
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: control-api
