apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: control-api
rules:
  - apiGroups:
      - 'batch'
    resources:
      - jobs
    verbs:
      - create
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
      - get